#!/usr/bin/env sh
# SPDX-License-Identifier: MIT
#
. /usr/local/AppCentral/cappysan-prometheus/.env.install

if test -f "${APKG_PKG_DIR}/active"; then
  export CERTBOT_RELOAD=0
  ${APKG_PKG_DIR}/CONTROL/start-stop.sh reload
fi

exit 0
