# SPDX-License-Identifier: MIT
#
---
# The following file enables recreating a templated output dir by executing:
#   mk-scaffold clone "https://gitlab.com/cappysan/scaffolds/asustor-template" --input-file .answers.yml --output-dir output
answers:
  - include: "~/.config/scaffold/answers.yml"
    optional: True

  - author: "Julien Lecomte"
  - email: "julien@cappysan.dev"

  - project_name: "cappysan-prometheus"
  - project_slug: "cappysan-prometheus"
  - project_url: "https://gitlab.com/cappysan/asustor/prometheus"
  - project_description: "Open-source monitoring system with a dimensional data model, flexible query language, efficient time series database and modern alerting approach."

  - has_documentation: False
  - documentation_url: ""

  - has_ci: True
  - has_pages: False
  - has_releases: True

  - has_precommit: True
  - has_precommit_codespell: True
  - has_precommit_nitpick: False

  - license: "MIT"
  - version: "3.12.0-r41"
  - version_style: "semver-rev"
  - copyright_string: "Cappysan, Julien Lecomte, and contributors"

  - keep_placeholders: False

  - template_url: "https://gitlab.com/cappysan/scaffolds/asustor-template"
  - template_version: "1.1.0-r4"

  - creation_year: "2025"
  - last_update: "2026-06-19 10:46:24"

  - maintainer: "Cappysan"
  - developer: "Cappysan"

  - app_name: "Prometheus"
  - cfg_name: "prometheus"
  - cappysan_name: "cappysan-prometheus"
  - asustor_name: "asustor-prometheus"

  - apk_description: ""
  - has_adm_desktop: True

  # Items without visible questions:
  - depends: '"python3(>=3.10.0)"'
  - adm_desktop_customizable: False
  - boot_priority_start: 70
  - boot_priority_stop: 30
  - has_upstream: True
