#!/usr/bin/env sh
#
set -eu

cd /usr/local/AppCentral/cappysan-prometheus

cat /usr/builtin/etc/certificate/ssl.pem /usr/builtin/etc/certificate/ssl.crt > ssl.crt
cp -f /usr/builtin/etc/certificate/ssl.key .
chown prometheus:0 ssl.*
chmod 600 ssl.*

./CONTROL/start-stop.sh reload
