---
scrape_configs:
  # This job monitors prometheus
  - job_name: "prometheus"
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: false
    file_sd_configs:
      - files:
          - "prometheus.d/*.yml"
    relabel_configs: &instance_relabel
      - source_labels: [__address__]
        target_label: instance
        regex: "([^:]+)(:[0-9]+)?"
        replacement: "${1}"
      - target_label: app
        replacement: prometheus
      - target_label: service
        replacement: prometheus
