#!/usr/bin/env sh
#
. /usr/local/AppCentral/cappysan-prometheus/.env.install
cd ${APKG_PKG_DIR:-/nonexistent} || exit 1

cd /usr/local/AppCentral/cappysan-prometheus

cat /usr/builtin/etc/certificate/ssl.pem /usr/builtin/etc/certificate/ssl.crt > ssl.crt
cp -f /usr/builtin/etc/certificate/ssl.key .
chown prometheus:0 ssl.*
chmod 600 ssl.*

./CONTROL/start-stop.sh reload
